# Site settings
title: "Systematic Analysis Framework"
description: "Achieving R=1.0 Certainty Through Rigorous Logical Elimination"
baseurl: "" # Leave empty for emergingpatterns.org
url: "https://emergingpatterns.org" # Your custom domain

# Theme
remote_theme: just-the-docs/just-the-docs
color_scheme: light # or dark

# Logo (optional - add logo.png to assets/images/)
# logo: "/assets/images/logo.png"

# Navigation
nav_sort: case_insensitive
nav_external_links:
  - title: "GitHub Repository"
    url: "https://github.com/emergingpatterns-org/emergingpatterns-org.github.io"
  - title: "Technical Downloads"
    url: "https://emergingpatterns.org/downloads"

# Search
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true

# Heading anchors
heading_anchors: true

# Footer
footer_content: "Copyright &copy; 2025 Emerging Patterns. Distributed under MIT License."

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Mermaid support (for diagrams)
mermaid:
  version: "9.1.6"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO
author: "Emerging Patterns"
twitter:
  username: emergingpatterns # if you have Twitter
  card: summary_large_image

# Google Analytics (optional)
# google_analytics: UA-XXXXXXXXX-X

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md # Exclude README from site build

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge